# Generated by Django 5.0.2 on 2024-02-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eventregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='institution',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
