# Generated by Django 5.0.2 on 2024-02-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_story_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
