# Generated by Django 5.0.2 on 2024-02-23 14:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_story_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
