# Generated by Django 5.0.2 on 2024-02-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='story',
        ),
    ]
